apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tutorial.fullname" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "tutorial.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tutorial.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        ports:
          - containerPort: 3000
