apiVersion: v1
kind: Service
metadata:
  name: {{ include "tutorial.fullname" . }}
  labels:
    {{- include "tutorial.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    {{- include "tutorial.selectorLabels" . | nindent 4 }}
